### ISSUE TITLE
빈 문자열 출력 문제

### ISSUE THREAD

**Issue by azza999** [jong-hui/JuJeob#14]
![image](https://user-images.githubusercontent.com/35221208/99141597-37e78d00-2690-11eb-9772-c17512592b87.png)

가끔씩 빈 문자열이 나옵니당

**Comment by jong-hui** [comment]
안녕하세여 도현님! 오랜만이네여 이슈 남겨주셔서 감사합니다 ㅎㅎ
해당 이슈는 확인됐는데, 왜 발생하는지 아직 모르겠네요.. 이번주내에 고칠 것 같습니다 👍

**Comment by jong-hui** [comment]
![image](https://user-images.githubusercontent.com/42797995/99267970-ee519a80-2867-11eb-8078-e006452f0715.png)

ㅎㅎ 실제 리스트중 하나가 {} 였군여,, 작업하다 배포된 듯 합니다

**Comment by azza999** [comment]
ㅎㅎ 즐프하세용 꾸준함이 부럽네요 ㅜㅜ
저는 기능대회 끝나고 한게 아무것도 없습니다 ㅜㅜ

**Comment by jong-hui** [comment]
저도 꾸준하진 않아요 ㅋㅋㅋㅋㅋ,,
제 입장에선 복무중에도 코딩하시는 게 놀랍습니다 ㅋㅋ 블로그 잘 볼게요
